# Generated by Django 3.1.5 on 2021-05-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210513_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='the_grade',
        ),
    ]
